config/routes.rb
Rails.application.routes.draw do
  root 'candidates#new'
  get '/new', to: 'candidates#new'
  post '/new' , to: 'cadidates#create'
  get '/show', to: 'candidates#show'
  get '/edit/:id', to: 'candidates#edit', as: 'edit'
  patch '/edit/:id', to:'candidates#update'
  delete '/destroy/:id', to:'candidates#destroy' , as: 'destroy'
  get '/view/:id', to: 'candidates#create_pdf', as:'create_pdf'
  get '/pdf/:id', to: 'candidates#pdf', as: 'pdf'
  # get 'candidates/report' ,as: 'create_pdf'
  resources :candidates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  NAME_REGEX = /^[a-zA-Z ]*$/
  validates :name,  presence: true, format: { with: NAME_REGEX , multiline:true, message: "can contain alphabets only" }
  validates :date,  presence: true
  ONLY_INTEGERS = /[1-9]\d*|0\d+/
  validates :installment_payment,  presence: true , format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
  validates :due_date,  presence: true
  validates :unit_no,  presence: true, format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
  validates :payment_plan,  presence: true
  validates :work_stage,  presence: true
  validates :installment_no,  presence: true, format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
  validates :cheque,  presence: true
  validates :account_no,  presence: true, format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
  validates :ifsc_code,  presence: true
  validates :bank_details,  presence: true
  validates :authorized_sign,  presence: true
  validates :due_amount, presence:true, format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
  validates :interest_on_delayed_payment,  presence: true , format: { with: ONLY_INTEGERS, multiline:true, message: "can contain numbers only" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to show_path
    else
      render 'new'
    end
  end

  def show
    @candidates = Candidate.all
  end

  def edit
    @candidate = Candidate.find(params[:id])
  end

  def update
    @candidate = Candidate.find(params[:id])

   if @candidate.update(candidate_params)
    redirect_to show_path
   else
    render 'edit'
   end
  end

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    redirect_to show_path
  end

  def pdf
    # @result_id = params[:id]
		content = create_pdf
		candidate_details = WickedPdf.new.pdf_from_string(content)
		save_path = "#{Rails.root}/public/candidates.pdf"
		File.open(save_path, 'wb') do |file|
		  file << candidate_details
		end
		redirect_to "/candidates.pdf" and return
  end

  def create_pdf
		@candidate = Candidate.find(params[:id])
    render_to_string :report, layout: false
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :date, :installment_payment, :due_date, :unit_no, :payment_plan, :work_stage, :installment_no, :cheque, :account_no, :ifsc_code, :bank_details, :authorized_sign, :due_amount, :interest_on_delayed_payment )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <div class="row">
    <div class="col-md-6">
      <div class="">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :date %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :installment_payment %>
        <%= f.text_field :installment_payment, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :due_date %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :unit_no %>
        <%= f.text_field :unit_no, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :payment_plan %>
        <%= f.text_field :payment_plan, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :work_stage %>
        <%= f.text_field :work_stage, class: 'form-control' %>
      </div>
      <div class="">
        <%= f.label :installment_no %>
        <%= f.text_field :installment_no, class: 'form-control' %>
      </div>
  </div>
  <div class="col-md-6">
    <div class="">
      <%= f.label :due_amount %>
      <%= f.text_field :due_amount, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :interest_on_delayed_payment %>
      <%= f.text_field :interest_on_delayed_payment, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :bank_name %>
      <%= f.text_field :bank_details, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :account_no %>
      <%= f.text_field :account_no, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :Ifsc_code %>
      <%= f.text_field :ifsc_code, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :cheque_no %>
      <%= f.text_field :cheque, class: 'form-control' %>
    </div>
    <div class="">
      <%= f.label :authorized_sign %>
      <%= f.text_field :authorized_sign, class: 'form-control' %>
    </div>
   </div>
   </div>
   <div class="button">
  <%= f.submit yield(:button_text), class: "btn btn-primary" %> </div>
<% end %>

app/views/candidates/_pdf_template.html.erb
<!DOCTYPE html>
<html lang="en">


<head>
<meta charset="utf-8" />
<title>project1</title>

</head>

<body>
<header>
	<!-- <img src="pdf1.PNG" alt="front page" width="100%" > -->
  <%= wicked_pdf_image_tag("#{request.protocol}#{request.host_with_port}/assets/pdf1.PNG" ,style:" width: 100%;" )  %>

</header>
<form style="font-family:;">

	<section style="margin-top:20px">
		<!-- <img src="logo.png" height:"236" width:"167" style="float:right;height:60px;width:40px;margin-right:20px;"> -->
    <%= wicked_pdf_image_tag("#{request.protocol}#{request.host_with_port}/assets/logo.png" , style:"float:right;height:60px;width:40px;margin-right:20px;" )  %>
    <center><div style="color:#DEB887;margin-top:90px;display:inline-block;"> DEMAND LETTER FOR PAYMENTS DUE</div></center>

	</section>
	<div style="float:right; margin-top:10px; margin-right:40px;">
	<span>Date</span><div style="width:130px;border-bottom:1px solid black;margin-left:10px;display:inline-block;"><%=
  @candidate.date %></div>
	</div>

	<div style="margin-top:10px;margin-left:60px;">
	<span>Mr./.Mrs/Ms</span><div style="width:145px;border-bottom:1px solid black;margin-left:10px;display:inline-block;">
    <%= @candidate.name %>
     </div><br><br>
	<div style="width:240px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"></div><br><br><br>
	<div style="width:240px;border-bottom:1px solid black;margin-left:3px;display:inline-block;margin-bottom:15px;line-height:22px;"></div>
	</div>

	<div style="margin-top:10px;margin-left:60px;">
	<div style="display:inline-block; line-height: 22px;margin-bottom:15px;"><b>Reg. Notice of Demand for <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.installment_payment %></center></div>    Installment Payment Due on   <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.due_date %></center></div>   against
	your UNIT No 	<div style="width:130px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.unit_no %></center></div> Studio/Service Apartment/Commercial Shop /Office Space booked in project 'CP.67' </b></div>


	</div>
	<div style="margin-top:10px;margin-left:60px;">
	<span>Dear Sir/Madam,</span>
	<div style="display:inline-block;margin-bottom:15px;line-height:22px;">kindly refer your booking for the aforesaid Unit No <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.unit_no %></center></div>     as per agreed <div style="width:80px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.payment_plan %></center></div>
	         payment plan.</div>

	</div>

	<div style="margin-top:10px;margin-left:60px;">
	<div style="display:inline-block;line-height:22px; "><b>Work Stage</b>  <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.work_stage %></center></div>          <b>   Installment no </b>   <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"> <center><%=
  @candidate.installment_no %></center> </div>   <b>   Due.</b>  <div style="width:100px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.due_amount %></center></div>
	   the following payment aginst your due installment is as under:</div>

	</div>

	<div style="margin-top:0px;margin-left:60px;">
	<p style="font-weight:bold; padding-top:50px;">DETAILS OF INSTALLMENT PAYMENT DUE</p>
	<p style="margin-top:0px;">A. CURRENT DUE</p>
	<table style="font-weight:normal;border-collapse:collapse;text-align:left;width:75%;" border="1">
		<thead>
		<th style="padding:10px;">Sr.No.</th>
		<th style="padding:10px;">Particulars</th>
		<th style="padding:10px;">Amount</th>

		</thead>
		<tbody>
		<tr><td style="padding:10px;">1.</td><td style="padding:10px;">Amount Due as per Payment Plan</td><td><%=
    @candidate.due_amount %></td></tr>
		<tr><td style="padding:10px;">2.</td><td style="padding:10px;">Add applicable GST</td><td><% gst =  @candidate.due_amount * 18/100 %>
    <%= gst %></td></tr>
		<tr><td style="padding:10px;">3.</td><td style="padding:10px;"><b>Total Amount Due(A)</b></td><td><% total_amount = gst + @candidate.due_amount %>
     <%= total_amount %></td></tr>

		</tbody>

	</table>

	</div>


	<div style="margin-top:0px;margin-left:60px;">

	<p style="margin-top:0px;">B. ARREARS DUE</p>
	<table style="font-weight:normal;border-collapse:collapse;text-align:left;width:75%;" border="1" >
		<thead>
		<th style="padding:10px;">Sr.No.</th>
		<th style="padding:10px;">Particulars</th>
		<th style="padding:10px;">Amount</th>

		</thead>
		<tbody>
		<tr><td style="padding:10px;">1.</td><td style="padding:10px;">Amount Due including GST</td><td style="padding:10px;"><%= total_amount %></td></tr>
		<tr><td style="padding:10px;">2.</td><td style="padding:10px;">Intrest on delayed payment</td><td style="padding:10px;"><%= @candidate.interest_on_delayed_payment %></td></tr>
		<tr><td style="padding:10px;">3.</td><td style="padding:10px;">Add GST on intrest amount</td><td style="padding:10px;"><% gst_on_interest = @candidate.interest_on_delayed_payment * 18/100 %>
    <%= gst_on_interest %></td></tr>
		<tr><td style="padding:10px;">4.</td><td style="padding:10px;"><b>Total amount of arrears (B)</b></td><td style="padding:10px;"><% b = total_amount + @candidate.interest_on_delayed_payment + gst_on_interest %>
    <%= b %></td></tr>
		</tbody>

	</table>


	<p style="display:inline-block;">TOTAL AMOUNT OF ARREARS & CURRENT DUE(A+B) Rs<div style="width:140px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center>3515220</center></div></div></p>
	</div>


	<section style="margin-top:150px">
		<!-- <img src="logo.png" height:"236" width:"167" style="float:right;height:60px;width:40px;margin-right:20px;"> -->
    <%= wicked_pdf_image_tag("#{request.protocol}#{request.host_with_port}/assets/logo.png" , style:"float:right;height:60px;width:40px;margin-right:20px;" )  %>
		<center><div style="color:#DEB887;margin-top:90px;display:inline-block;"> DEMAND LETTER FOR PAYMENTS DUE</div></center>

	</section>
	<div style="margin-top:10px;margin-left:60px;">
	you are hereby,requested to kindlay arrange to deposite the said DUE amount with seven days from the<br>
	date of demand letter to avoid applicable intrest charges.<br>
	payments to bedrawn in favor of:

	<table style="margin-top:40px; ">
	<tr><td>Cheque/DD/NEFTRTGS.</td><td>:</td><td style="padding-left:10px;"><%=
  @candidate.cheque %></td></tr>
	<tr><td>Bank Account No.</td><td>:</td><td style="padding-left:10px;"><%=
  @candidate.account_no%></td></tr>
	<tr><td>IFCS Code for NEFT/RTGS</td><td>:</td><td style="padding-left:10px;"><%=
  @candidate.ifsc_code %></td></tr>
	<tr><td>Bank Branch details</td><td>:</td><td style="padding-left:10px;"><%=
  @candidate.bank_details %></td></tr>

	</table>
	<p>Assuring you of our best services at all times for mutual benifits,</p>
	<p>Thanking you,</p>


	<p style="display:inline-block;">(<div style="width:130px;border-bottom:1px solid black;margin-left:3px;display:inline-block;"><center><%=
  @candidate.authorized_sign %></center></div>)</p>
	<p> Authorised Signatory</p>
	<p>AB ALCOBEV PVT. LTD.</p>

	<p>-In case of any query you may contact us at e-mail at info@cp67.co.in <br>
	   -In case of payment aleready made,pls send details to reconcile & update accounts.<br>
	   -Intrest on delayed payments will be charged @18% pa,as perterms of the application 	/allotment,time<br>
	   being essence of the contract.
	</p>
	</div><br>
	</form>

<footer >
<!-- <img src="pdf2.PNG" alt="DESCRIPTION" width="100%"> -->
<%= wicked_pdf_image_tag("#{request.protocol}#{request.host_with_port}/assets/pdf2.PNG" ,style:" width: 100%;" )  %>
</footer>

</body>

</html>

app/views/candidates/create_pdf.html.erb
<%= link_to 'Show ALL', show_path %>
<%= render 'pdf_template', object:@candidate %>

app/views/candidates/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<h1 class="text-center">Update User</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/candidates/new.html.erb
<% provide(:button_text, 'Add New User') %>
<h1 class="text-center">Add New User</h1>
<div class="row">
  <%= link_to 'Show All', show_path %>
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div

app/views/candidates/report.html.erb
<%= render 'pdf_template', object:@candidate %>

app/views/candidates/show.html.erb
<h1 class="text-center">List of All Users</h1>
<%= link_to 'Add new User', new_path %>
<table class="table">
  <thead>
    <tr>
    <th>
      Name
    </th>
    <th>
      Installment Payment
    </th>
    <th>
      Due Date
    </th>
    <th>
      Unit No.
    </th>
    <th>
      Payment Plan
    </th>
    <th>
      Work Stage
    </th>
    <th>
      Installment Number
    </th>
    <th>
      Due Amount
    </th>
    <th>
      Interest On Delayed Payment
    </th>
    <th>
      Cheque No.
    </th>
    <th>
      Account No.
    </th>
    <th>
      IFSC code
    </th>
    <th>
      Bank Details
    </th>
    <th>
      Authorized Sign
    </th>
    <th colspan="4">
      Actions
    </th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td>
        <%= candidate.name %>
      </td>
      <td>
        <%= candidate.installment_payment %>
      </td>
      <td>
        <%= candidate.due_date %>
      </td>
      <td>
        <%= candidate.unit_no %>
      </td>
      <td>
        <%= candidate.payment_plan %>
      </td>
      <td>
        <%= candidate.work_stage %>
      </td>
      <td>
        <%= candidate.installment_no %>
      </td>
      <td>
        <%= candidate.due_amount %>
      </td>
      <td>
        <%= candidate.interest_on_delayed_payment %>
      </td>
      <td>
        <%= candidate.cheque %>
      </td>
      <td>
        <%= candidate.account_no %>
      </td>
      <td>
        <%= candidate.ifsc_code %>
      </td>
      <td>
        <%= candidate.bank_details %>
      </td>
      <td>
        <%= candidate.authorized_sign %>
      </td>
      <td>
        <%= link_to 'View' , create_pdf_path(candidate.id) %>
      </td>
      <td>
        <%= link_to 'Edit' , edit_path(candidate.id) %>
      </td>
      <td>
        <%= link_to 'Delete', destroy_path( candidate.id),     method: :delete,
        data: { confirm: 'Are you sure?' } %>
      </td>
      <td>
        <%= link_to 'Demand Letter PDF' , pdf_path( candidate.id) , :target =>  "_blank" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemandLetterPdfApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @candidate.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@candidate.errors.count, "error") %>.
    </div>
    <ul>
    <% @candidate.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>